web:
  build: .
  ports:
    - "80:80"
  volumes:
    - ./app:/var/www/html
  links:
    - db
db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
    MYSQL_DATABASE: docker
