web:
    build: .
    command: php -S 0.0.0.0:8000 -t /app
    ports:
        - "8000:8000"
    volumes:
        - .:/app
    links:
        - db
db:
    image: mariadb
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: docker_database
phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
        - db:mysql
    ports:
        - 8181:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
